version: '3'
services:
  frontend:
    build:
      context: frontend
    container_name: frontend
    restart: always
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - bridge

  backend:
    build:
      context: backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - redis
    networks:
      - bridge

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  redis_data: